#!/bin/sh

DAEMON="lvgl_main"
EXECUTABLE="/usr/bin/$DAEMON"

LVGL_ARGS=""

function moduleExist() {
	MODULE="$1"
	if lsmod | grep "$MODULE" &> /dev/null ; then
		return 0
	else
		return 1
	fi
}

start() {
	printf 'Starting %s: ' "$DAEMON"
	if moduleExist "dcultrafb" ; then
		echo "dcultrafb already loaded"
	else
		insmod /lib/modules/`uname -r`/dcultrafb.ko
	fi
	
	if moduleExist "galcore" ; then
		echo "galcore already loaded"
	else
		insmod /lib/modules/`uname -r`/galcore.ko
	fi

	start-stop-daemon -b -S -q -x "$EXECUTABLE" \
		-- $LVGL_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -x "$EXECUTABLE"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	# we do not support real reload .. just restart
	restart
}

case "$1" in
    start|stop|restart|reload)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
